### ISSUE TITLE
Mere presence of any `workspace` settings in `Cargo.toml` triggers analysis of workspace members

### ISSUE THREAD

**Issue by bbannier** [TimonPost/cargo-unused-features#22]
I am working on a project which uses a `cargo-dist`-generated `workspace` section, e.g.,

```toml
# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.17.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = true
```

The project has no workspace members, so if I run `analyze` on the project nothing gets analyzed (similar to #21).
